### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by cstjean** [tkoolen/TypeSortedCollections.jl#31]
I'm a little confused about the interface for mapping. How would I perform the equivalent of

`Set(size(x) for x in some_type_sorted_collection)` ?

Is there a function like `map_to_set`, or `map_to_vector`? Why isn't `map(::Function, ::TypeSortedCollection)` supported?

**Comment by tkoolen** [comment]
For my own work, I need things to not allocate at all (after an initial preallocation phase), so I just implemented the in-place version (`map!`). There's also quite a bit of additional complexity in figuring out the correct element type of the `Vector` to return. Additionally, it's not 100% clear whether the user would want a `Vector` or a `TypeSortedCollection` back from `map` (which could be clarified using a new `map_to_vector` function, as you proposed).

For now I would recommend

```julia
julia> using Compat

julia> x = [rand(3), rand(2), view(rand(2), 1:2), view(rand(2, 2), 1:2)];

julia> tsc = TypeSortedCollection(x);

julia> Set(map!(size, Vector{Tuple{Int}}(undef, length(tsc)), tsc))
Set(Tuple{Int64}[(3,), (2,)])
```

i.e., being explicit about what return type you want.

`TypeSortedCollection`s could also implement the iterator interface so that `Set(size(x) for x in some_type_sorted_collection)` (generators) would just work, but that would necessarily be type-unstable and hence lack performance, which would be surprising for users.

**Comment by cstjean** [comment]
The `map!` solution is nice, thank you. I wonder if `map!(size, Set{Int}(), tsc)` would make sense. It's not supported for `::Vector` inputs, but it seems reasonable enough.

EDIT: I guess it's semantically awkward if the `Set` already has values in it.
